"""
Config Sync Lambda

Extracts frontend-relevant configuration from profiler-config.json and
generates a frontend-config.json file for the frontend to consume.

This enables:
1. Single source of truth for region/provider configuration
2. Automatic frontend config updates when backend config changes
3. Gap detection for frontend config drift
"""

import json
import logging
import os
import time
from typing import Any

from shared import (
    get_s3_client,
    read_from_s3,
    write_to_s3,
    parse_execution_id,
    validate_required_params,
    ValidationError,
    get_config_loader,
)

logger = logging.getLogger()
logger.setLevel(os.environ.get("LOG_LEVEL", "INFO"))


def extract_frontend_config(backend_config: dict) -> dict:
    """
    Extract frontend-relevant configuration from backend config.

    Returns a frontend-optimized config structure.
    """
    region_config = backend_config.get("region_configuration", {})
    provider_config = backend_config.get("provider_configuration", {})
    model_config = backend_config.get("model_configuration", {})

    # Build region metadata for frontend
    regions = {}
    region_locations = region_config.get("region_locations", {})
    region_coordinates = region_config.get("region_coordinates", {})

    for region_code, location_name in region_locations.items():
        coords = region_coordinates.get(region_code, {})
        regions[region_code] = {
            "label": coords.get("name", location_name.split("(")[0].strip()),
            "fullName": location_name,
            "geo": coords.get("geo", "US"),
            "lat": coords.get("lat"),
            "lng": coords.get("lng"),
        }

    # Build AWS regions list for dropdowns
    aws_regions = []
    for region in region_config.get("aws_regions", []):
        aws_regions.append(
            {
                "value": region.get("value"),
                "label": region.get("label"),
                "geo": region.get("geo"),
            }
        )

    # Build geo region options
    geo_region_options = region_config.get("geo_region_options", [])

    # Build provider colors
    provider_colors = provider_config.get("provider_colors", {})

    # Build provider documentation links
    documentation_links = provider_config.get("documentation_links", {})

    # Build context window thresholds
    context_thresholds = model_config.get(
        "context_window_thresholds", {"small": 32000, "medium": 128000, "large": 500000}
    )

    return {
        "version": backend_config.get("version", "1.0.0"),
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "source": "profiler-config.json",
        "regions": regions,
        "aws_regions": aws_regions,
        "geo_region_options": geo_region_options,
        "geo_prefix_map": region_config.get("geo_prefix_map", {}),
        "providers": {"colors": provider_colors, "documentation": documentation_links},
        "model_config": {
            "context_thresholds": context_thresholds,
            "model_families": model_config.get("model_families", []),
            "model_variants": model_config.get("model_variants", []),
        },
    }


def generate_js_constants(frontend_config: dict) -> str:
    """
    Generate JavaScript constants file content from frontend config.

    This can be used to generate frontend/src/config/generated-constants.js
    """
    js_content = f'''/**
 * Auto-generated constants from backend profiler-config.json
 * Generated at: {frontend_config.get("generated_at")}
 * Source version: {frontend_config.get("version")}
 * 
 * DO NOT EDIT MANUALLY - This file is auto-generated by config-sync Lambda
 */

// Provider Colors
export const providerColors = {
        json.dumps(frontend_config.get("providers", {}).get("colors", {}), indent=2)
    };

// Region Coordinates
export const regionCoordinates = {
        json.dumps(
            {
                code: {
                    "lat": data.get("lat"),
                    "lng": data.get("lng"),
                    "name": data.get("label"),
                    "geo": data.get("geo"),
                }
                for code, data in frontend_config.get("regions", {}).items()
                if data.get("lat") is not None
            },
            indent=2,
        )
    };

// AWS Regions for dropdowns
export const awsRegions = {
        json.dumps(frontend_config.get("aws_regions", []), indent=2)
    };

// Geographic region options
export const geoRegionOptions = {
        json.dumps(frontend_config.get("geo_region_options", []), indent=2)
    };

// Geo prefix map
export const geoPrefixMap = {
        json.dumps(frontend_config.get("geo_prefix_map", {}), indent=2)
    };

// Context window thresholds
export const contextWindowThresholds = {
        json.dumps(
            frontend_config.get("model_config", {}).get("context_thresholds", {}),
            indent=2,
        )
    };

// Config metadata
export const configMetadata = {{
  version: "{frontend_config.get("version")}",
  generatedAt: "{frontend_config.get("generated_at")}",
  source: "{frontend_config.get("source")}"
}};
'''
    return js_content


def lambda_handler(event: dict, context: Any) -> dict:
    """
    Lambda handler for config sync.

    Input:
        {
            "s3Bucket": "bucket-name",
            "executionId": "exec-123",
            "generateJs": true/false (optional, default false)
        }

    Output:
        {
            "status": "SUCCESS",
            "frontendConfigS3Key": "config/frontend-config.json",
            "jsConstantsS3Key": "config/generated-constants.js" (if generateJs=true),
            "configVersion": "1.0.0"
        }
    """
    start_time = time.time()

    # Validate required parameters
    try:
        validate_required_params(event, ["s3Bucket"], "ConfigSync")
    except ValidationError as e:
        return {
            "status": "FAILED",
            "errorType": "ValidationError",
            "errorMessage": str(e),
        }

    s3_bucket = event["s3Bucket"]
    execution_id = parse_execution_id(event.get("executionId", "manual"))
    generate_js = event.get("generateJs", False)

    logger.info(f"Running config sync for execution {execution_id}")

    try:
        s3_client = get_s3_client()

        # Load backend config
        config_loader = get_config_loader()
        backend_config = config_loader.config

        # Extract frontend config
        frontend_config = extract_frontend_config(backend_config)

        # Write frontend config to S3
        frontend_config_key = "config/frontend-config.json"
        write_to_s3(s3_client, s3_bucket, frontend_config_key, frontend_config)
        logger.info(f"Wrote frontend config to s3://{s3_bucket}/{frontend_config_key}")

        result = {
            "status": "SUCCESS",
            "frontendConfigS3Key": frontend_config_key,
            "configVersion": frontend_config.get("version"),
            "regionsCount": len(frontend_config.get("regions", {})),
            "providersCount": len(
                frontend_config.get("providers", {}).get("colors", {})
            ),
        }

        # Optionally generate JS constants file
        if generate_js:
            js_content = generate_js_constants(frontend_config)
            js_key = "config/generated-constants.js"
            s3_client.put_object(
                Bucket=s3_bucket,
                Key=js_key,
                Body=js_content.encode("utf-8"),
                ContentType="application/javascript",
            )
            result["jsConstantsS3Key"] = js_key
            logger.info(f"Wrote JS constants to s3://{s3_bucket}/{js_key}")

        duration_ms = int((time.time() - start_time) * 1000)
        result["durationMs"] = duration_ms

        return result

    except Exception as e:
        logger.error(f"Failed to sync config: {e}", exc_info=True)
        return {
            "status": "FAILED",
            "errorType": type(e).__name__,
            "errorMessage": str(e),
        }
