version = 0.1

[default.deploy.parameters]
stack_name = "bedrock-profiler-dev"
resolve_s3 = true
s3_prefix = "bedrock-profiler-dev"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "Environment=\"dev\" ScheduleEnabled=\"false\""
